routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');

Route::get('u/{user}', 'ProfileController@show')->name('profile');
Route::get('settings', 'UserSettingsController@show')->name('settings')->middleware('auth');
Route::post('settings/password', 'UserSettingsController@storePassword')->name('settings.storepassword')->middleware('auth');

Route::post('c', 'ChannelController@store')->name('channel.store')->middleware('auth');
Route::get('c/{channel}/create', 'ThreadController@create')->name('thread.create')->middleware('auth');
Route::post('c/{channel}/thread/store', 'ThreadController@store')->name('thread.store');
Route::get('c/{channel}/thread/{thread}', 'ThreadController@show')->name('thread.show');
Route::post('c/{channel}/thread/{thread}/report', 'ThreadController@report')->name('thread.report');
Route::post('c/{channel}/thread/{thread}/reply', 'ReplyController@store')->name('thread.reply');


//Route::pattern('channel', '(?i)channel(?-i)');
Route::get('c/{channel}', 'ChannelController@show')->name('channel.show');

Route::post('c/{channel}/subscribe', 'ChannelSubscriptionController@store')->name('channel.subscribe');
Route::post('c/{channel}/unsubscribe', 'ChannelSubscriptionController@destroy')->name('channel.unsubscribe');

require '_admin.php';

app/Models/Thread.php
<?php

namespace App\Models;

use App\Traits\RecordsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Thread extends Model
{

    use RecordsActivity;

    use SoftDeletes;

    protected $guarded = [];

    protected $with = ['user'];

    /**
     * A Thread has a creator
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    /**
     * A Thread can have many Replies
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    /**
     * A Thread belongs to a Channel
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function channel()
    {
        return $this->belongsTo(Channel::class);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
//        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $threads = \App\Models\Thread::with('channel')
            ->with('user')
            ->withCount('replies')
            ->latest()
            ->paginate(10);

        return view('index')->with(compact('threads'));
    }
}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Models\Channel;
use App\Models\Reply;
use App\Models\Thread;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class ThreadController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Channel $channel
     * @return void
     */
    public function create(Channel $channel)
    {
        return view('threads.create')->with(compact('channel'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Channel $channel
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(Channel $channel, Request $request)
    {
        request()->validate([
            'title' => 'required|min:6',
            'channel_id' => ['required', Rule::exists('channels', 'id')],
        ]);

        $thread = Thread::create([
            'title' => $request->title,
            'body' => $request->body,
            'user_id' => auth()->id(),
            'channel_id' => $request->channel_id,
        ]);

        flash("You've added a new thread!");

        return redirect(route('thread.show', [$channel, $thread]));
    }

    /**
     * Display the specified resource.
     *
     * @param Channel $channel
     * @param  \App\Models\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function show(Channel $channel, Thread $thread)
    {
        $replies = Reply::with('user')->whereThreadId($thread->id)->latest()->paginate(20);

        $thread->increment('views');

        return view('threads.show')->with(compact('thread', 'replies'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Channel $channel, Thread $thread)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Channel $channel, Thread $thread)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Thread $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy(Channel $channel, Thread $thread)
    {
        //
    }
}

resources/views/threads/_form_reply.blade.php
@csrf
<textarea
        name="body"
        rows="3"
        class="card w-full mb-4 bg-grey-lightest"
        placeholder="Please be civil..."
        style="resize:none"
>{{ $reply->body }}</textarea>
<button type="submit" class="button is-link mr-2 rounded-sm">{{ $buttonText }}</button>

resources/views/threads/_front.blade.php
<div class="card">
    <div><a href="{{ route('thread.show', [$thread->channel, $thread]) }}" class="no-underline text-blue-darker">
            {{ $thread->title }}
        </a>
        <a href="#" class="no-underline text-xs text-grey-dark">(domain.com)</a>
    </div>
    <div class="text-grey-dark text-xs">
        submitted {{ $thread->created_at->diffForHumans() }} by
        <a href="{{ route('profile', $thread->user) }}"
           class="no-underline text-blue-dark">{{ $thread->user->name }}</a>
        in
        <a href="{{ route('channel.show', $thread->channel) }}"
           class="no-underline text-blue-dark">c/{{ $thread->channel->name }}</a>
    </div>
    <div>
        <a href="{{ route('thread.show', [$thread->channel, $thread]) }}" class="no-underline text-blue-dark text-sm">
            {{ $thread->replies_count }} comments</a>
    </div>

</div>

resources/views/threads/_reply.blade.php
<div class="card">
    <div class="card-body">
        <p class="mb-2">
            <a href="{{ route('profile', $reply->user) }}" class="no-underline text-sm">{{ $reply->user->name }}</a>
            <span class="text-xs">
                replied <a title="{{ $reply->created_at }}">{{ $reply->created_at->diffForHumans() }}</a>:
            </span>
        </p>
        <p class="ml-2 mr-2">{{ $reply->body }}</p>
    </div>
</div>

resources/views/threads/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <h2>Create a new post in c/{{ $channel->name }}</h2>
    </div>

    <div>
        <form action="{{ route('thread.store', $channel) }}" method="POST">
            @csrf
            <input type="text" name="title" id="title">
            <textarea name="body"></textarea>

            <button type="submit">Submit post</button>
        </form>
    </div>

@endsection

resources/views/threads/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header text-lg mb-4"><span class="font-bold">{{ $thread->title }}</span>
                    <span class="text-sm">
                        by
                        <a href="{{ route('profile', $thread->user) }}" class="no-underline">{{ $thread->user->name }}</a>
                        submitted
                        <span title="{{ $thread->created_at }}">{{ $thread->created_at->diffForHumans() }}</span>
                    </span>
                </div>
                <div class="bg-grey-lightest shadow border border-grey rounded p-2">
                    {{ $thread->body }}
                </div>

                <div class="card-footer text-sm mt-2">
                    Showing {{ $replies->count() }} replies...
                </div>
            </div>

        </div>
    </div>

    <div class="card">
        <form action="{{ route('thread.reply', [$thread->channel, $thread]) }}" method="post">

            @include('threads._form_reply', [
                            'reply' => new \App\Models\Reply,
                            'buttonText' => 'Submit Reply'
                        ])
        </form>
    </div>

    @foreach($replies as $reply)
        @include('threads._reply')
    @endforeach

    {{ $replies->links() }}
@endsection